pausas_activas/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from core.views import IndexTemplateView, IndexDetailView

urlpatterns = [
    path('_nested_admin/', include('nested_admin.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', login_required(IndexTemplateView.as_view()), name='home'),
    path('pausa-activa/<slug:slug>/', login_required(IndexDetailView.as_view()), name='home_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from colorfield.fields import ColorField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.utils.text import slugify


class Company(models.Model):
    owner = models.OneToOneField(User, verbose_name='Usuario dueño', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Nombre de la empresa', max_length=100)
    logo = models.ImageField(verbose_name='Logo de la empresa', upload_to='company/logos/')
    mascot = models.FileField(verbose_name='Mascota de la empresa', upload_to='company/mascots/')
    primary_color = ColorField(verbose_name='Color primario de la empresa', default='#4a5bb2')
    secondary_color = ColorField(verbose_name='Color secundario de la empresa', default='#a48421')

    class Meta:
        verbose_name = 'Empresa'
        verbose_name_plural = 'Empresas'

    def __str__(self):
        return f'{self.name}'


class ActivePause(models.Model):
    company = models.ForeignKey(Company, verbose_name='Empresa', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Nombre de la pausa activa', max_length=100)
    slug = models.SlugField(db_index=True, verbose_name='Ruta Web', max_length=150)
    description = models.TextField(verbose_name='Descripción', max_length=100, blank=True, null=True)
    image = models.ImageField(verbose_name='Imágen', upload_to='active-pauses/images/', blank=True, null=True)
    icon_svg = models.FileField(verbose_name='Icono en SVG', upload_to='active-pauses/icons/', blank=True, null=True)
    number_of_exercises = models.IntegerField(verbose_name='Número de ejercicios', default=0)
    duration = models.CharField(verbose_name='Duración', max_length=10)

    class Meta:
        verbose_name = 'Pausa Activa'
        verbose_name_plural = 'Pausas Activas'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(ActivePause, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}'


class Activity(models.Model):
    active_pause = models.ForeignKey(ActivePause, verbose_name='Pausa activa', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Nombre de la actividad', max_length=100)

    class Meta:
        verbose_name = 'Actividad'
        verbose_name_plural = 'Actividades'

    def __str__(self):
        return f'{self.name}'


class Prevent(models.Model):
    active_pause = models.ForeignKey(ActivePause, verbose_name='Pausa activa', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Nombre de la prevención', max_length=100)

    class Meta:
        verbose_name = 'Que previene'
        verbose_name_plural = 'Que previene'

    def __str__(self):
        return f'{self.name}'


class Video(models.Model):
    active_pause = models.ForeignKey(ActivePause, verbose_name='Pausa activa', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Nombre del video', max_length=100)
    image = models.ImageField(verbose_name='Imágen', upload_to='active-pauses/videos/images/', blank=True, null=True)
    video = models.FileField(verbose_name='Video', upload_to='active-pauses/videos/', blank=True, null=True)

    class Meta:
        verbose_name = 'Video'
        verbose_name_plural = 'Videos'

    def __str__(self):
        return f'{self.name}'

core/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView, DetailView

from core.models import Company, Activity, ActivePause, Prevent


class IndexTemplateView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        company = Company.objects.first()
        pauses = ActivePause.objects.filter(company=company)
        context['company'] = company
        context['pauses'] = pauses
        return context


class IndexDetailView(DetailView):
    template_name = 'pause-detail.html'
    model = ActivePause
    context_object_name = 'pause'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        company = Company.objects.first()
        pauses = ActivePause.objects.filter(company=company)
        context['company'] = company
        context['pauses'] = pauses
        return context

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Pausas Activas{% endblock %}</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
    {% block custom_css %}
    {% endblock %}
    {% block materialize %}
        <link rel="stylesheet" href="{% static 'core/css/materialize.min.css' %}">
    {% endblock %}
    <link rel="stylesheet" href="{% static 'core/css/custom_style.css' %}" type="text/css"
          media="screen,projection"/>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

</head>
<body>
<main>
    {% block nav %}
        <nav>
            <div class="nav-wrapper blue">
                <a href="{% url 'home' %}" class="brand-logo">Pausas Activas</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a href="{% url 'home' %}">Inicio</a></li>
                    <li><a href="{% url 'admin:index' %}">Administrador</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'logout' %}">Cerrar sesión</a></li>{% endif %}
                </ul>
            </div>
        </nav>
    {% endblock %}

    {% block content %}
    {% endblock %}
</main>
<!-- Compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="{% static 'core/js/materialize.js' %}"></script>
<script src="{% static 'core/js/custom_js.js' %}"></script>
{% block custom_js %}
{% endblock %}
</body>
{% block footer %}
    <footer class="page-footer blue footer-fixed">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Pausas activas</h5>
                    <p class="grey-text text-lighten-4">Este sistema permite automatizar gestionar el proceso de pausas
                        activas en personas de oficina.</p>
                </div>
                <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Enlaces de interés</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                © 2021 Copyright - Diego A Asencio C
                <a class="grey-text text-lighten-4 right" href="#!">versión 0.0.1</a>
            </div>
        </div>
    </footer>
{% endblock %}
</html>

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Pausas activas</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'core/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static 'core/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>

<header class="top-nav">
    <nav class="nav-extended">
        <div class="nav-wrapper center" style="background-color: {{ company.primary_color }}">
            <a class="brand-logo center" style="background-color: {{ company.primary_color }};" href="{% url 'home' %}">
                <h5>Pausas activas - {{ company.name }}</h5>
            </a>
            <ul id="dropdown1" class="dropdown-content">
                <li><a href="#!"></a></li>
                <li class="divider"></li>
                <li><a href="#!">Cerrar sesión</a></li>
            </ul>
            <ul class="right hide-on-med-and-down">
                <li><a href="{% url 'home' %}">Inicio</a></li>
                <!-- Dropdown Trigger -->
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">{{ user }}<i
                        class="material-icons right">arrow_drop_down</i></a></li>
            </ul>
        </div>
    </nav>
</header>
<div class="container">

    <div class="section center-hor-ver">
        <!--   Icon Section   -->
        <div class="row">
            <div class="col s12 m4 l4 offset-l1 offset-m1 right-align"
                 style="background-color: {{ company.primary_color }}">
                <div class="icon-block" style="width: auto; height: 600px">
                    {% if company.mascot %}
                        <img src="/media/{{ company.mascot }}" width="50%">
                    {% else %}
                        <img src="{% static 'core/images/coviamigo.gif' %}" width="50%">
                    {% endif %}
                    <h5 class="white-text">Actividades</h5>

                    <p class="white-text light">Es hora de tu pausa activa</p>
                    <h5 class="white-text">Unos minutos al día</h5>

                    <p class="white-text light">Recupera energía, mejora tu desempeño y eficiencia</p>
                </div>
            </div>

            <div class="col s12 m6 l6" style="background-color: {{ company.secondary_color }}">
                <div class="carousel scale-transition" id="demo-carousel" style="width: auto; height: 600px">
                    {% if pauses %}
                        {% for pause in pauses %}
                            <div class="carousel-item">
                                <div class="card"
                                     style="background-color: {{ company.primary_color }}; top: -50%;">
                                    <div class="card-image">
                                        <a href="#"><img src="/media/{{ pause.image }}"></a>
                                    </div>

                                    <div class="card-action left-align">
                                        <h6 class="white-text"><b>{{ pause.name }}</b></h6>
                                        <p class="grey-text">Duración: {{ pause.duration }}</p>
                                        <p class="grey-text">N° de Ejercicios: {{ pause.number_of_exercises }}</p>
                                        <br>
                                        <a href="{% url 'home_detail' slug=pause.slug %}">Ver ahora</a>
                                        <br>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="carousel-item card blue darken-4">
                            <div class="card-image">
                                <a href="#"><img src="{% static 'core/images/1.jpg' %}"></a>
                            </div>

                            <div class="card-action left-align">
                                <p>Ejemplo de pausa activa</p>
                                <a href="#">Ver ahora</a>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>

        </div>

    </div>

</div>


<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="{% static 'core/js/materialize.js' %}"></script>
<script src="{% static 'core/js/init.js' %}"></script>
<script src="{% static 'core/js/slider.js' %}"></script>

</body>
</html>

templates/pause-detail.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Pausas activas</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'core/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static 'core/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>

<header class="top-nav">
    <nav class="nav-extended">
        <div class="nav-wrapper center" style="background-color: {{ company.primary_color }}">
            <a class="brand-logo center" style="background-color: {{ company.primary_color }};" href="{% url 'home' %}">
                <h5>Pausas activas - {{ company.name }}</h5>
            </a>
            <ul id="dropdown1" class="dropdown-content">
                <li><a href="#!"></a></li>
                <li class="divider"></li>
                <li><a href="#!">Cerrar sesión</a></li>
            </ul>
            <ul class="right hide-on-med-and-down">
                <li><a href="{% url 'home' %}">Inicio</a></li>
                <!-- Dropdown Trigger -->
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">{{ user }}<i
                        class="material-icons right">arrow_drop_down</i></a></li>
            </ul>
        </div>
    </nav>
</header>
<div class="container">

    <div class="section center-hor-ver">
        <!--   Icon Section   -->
        <div class="row">
            <div class="col s12 m4 l4 offset-l1 offset-m1 right-align"
                 style="background-color: {{ company.primary_color }}">
                <div class="icon-block" style="width: auto; height: 600px">
                    {% if company.mascot %}
                        <img src="/media/{{ company.mascot }}" width="50%">
                    {% else %}
                        <img src="{% static 'core/images/coviamigo.gif' %}" width="50%">
                    {% endif %}
                    <h5 class="white-text">Actividades</h5>
                    {% for activity in pause.activity_set.all %}
                        <p class="white-text light">{{ activity.name }}</p>
                    {% endfor %}
                    <h5 class="white-text">¿Qué previene?</h5>
                    {% for prevent in pause.prevent_set.all %}
                        <p class="white-text light">{{ prevent.name }}</p>
                    {% endfor %}
                </div>
            </div>

            <div class="col s12 m6 l6" style="background-color: {{ company.secondary_color }}">
                <div class="row" style="width: auto; height: 580px">
                    {% for video in pause.video_set.all|slice:":6" %}
                        <div class="col s12 m6 l4">
                            <div class="card blue darken-4">
                                <div class="card-image">
                                    <img src="/media/{{ video.image }}">
                                </div>
                                <div class="card-action">
                                    <a href="#video-{{ video.id }}" class="modal-trigger">{{ video.name }}</a>
                                    <div id="video-{{ video.id }}" class="modal modal-fixed-footer"
                                         style="background-color: {{ company.primary_color }}">
                                        <div class="modal-content center">
                                            <h4>{{ video.name }}</h4>
                                            <br>
                                            <video id="video-{{ video.id }}" controls width=100% height="400px"
                                            src="/media/{{ video.video }}"></video>
                                        </div>
                                        <div class="modal-footer" style="background-color: {{ company.primary_color }}">
                                            <a href="#!" onclick="pausar()"
                                               class="modal-close waves-effect waves-green btn-flat">Cerrar</a>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>

                    
                    {% endfor %}

                </div>
            </div>

        </div>

    </div>

</div>
<!--  Scripts-->

<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="{% static 'core/js/materialize.js' %}"></script>
<script src="{% static 'core/js/init.js' %}"></script>
<script src="{% static 'core/js/ventana.js' %}"></script>

</body>
</html>